### ISSUE TITLE
Integration of Antenna Reset Feature for SMLight

### ISSUE THREAD

**Issue by gluoncompany** [smlight-tech/pysmlight#14]
Hi tl-sl,

I hope you're doing well. I noticed your excellent work on integrating the SMLight antennas to monitor their temperature. I wanted to share with you a custom component I've developed that adds functionality to reset the Zigbee and ESP32 antennas via Home Assistant services.

You can find the code in my GitHub repository: https://github.com/gluoncompany/smlightreset/
Feel free to check it out, and if you think it would be a good fit, perhaps we could integrate it with your existing codebase.

Let me know your thoughts, and I'd be happy to collaborate on this!

Best regards,

**Comment by tl-sl** [comment]
Hi @gluoncompany,
  Thanks for the link, the initial release of integration was only the bare minimum to get the base implemented. There are a huge number of updates to  SMLIGHT integration queued for the 2024.10 HA release (currently available in `dev` channel for testing). Included in this release will be buttons to reset Zigbee and ESP32 and lots of other goodies ( firmware updates, led controls and lots more sensors etc).
  
 You can checkout the latest code here:
  https://github.com/home-assistant/core/tree/dev/homeassistant/components/smlight
  
 I haven't so far implemented any services, but would be happy to add these where it makes sense (however in case of resets, you can probably just use the button entities in automations?). If you wish to contribute you can create PR's against the official integration!

![image](https://github.com/user-attachments/assets/dcf88b25-17a0-43bb-9c56-ad8c5b0986c3)

**Comment by gluoncompany** [comment]
I've been reviewing your code and it's great, I'm looking forward to the new version. We've used the reset service to include it in automations. If the integration itself can be called from automations, the service wouldn't be necessary.

Thank you very much, great work!

**Comment by tl-sl** [comment]
Yes you would just do something like this in your automation:

```
action: button.press
target:
  entity_id: button.slzb_06_core_restart
data: {}
```

**Comment by tl-sl** [comment]
I will close this now, but feel free to open another issue if you have any feature requests or contributions for the updated version next release.
